#!/bin/sh

used() { 
    echo $(df -h / | awk '{print $3}' | tail -1 | sed 's/G//')
}

total() {
    echo $(df -h / | awk '{print $2}' | tail -1 | sed 's/G//')

}

percent() {
    echo $(df -h / | awk '{print $5}' | tail -1 | sed 's/%//')
}

if [ "$1" = "used" ];then
    used
elif [ "$1" = "total" ];then
    total
elif [ "$1" = "percent" ];then
    percent
else
    echo "unknown option"
fi
