#!/bin/bash

function percent () {
    echo $(pamixer --get-volume)
}

function icon() {
    local per=$(pamixer --get-volume)
    local muted=$(pamixer --get-mute)

    if [ "$muted" = "true" ]; then
        echo ""
    elif (( per >= 60 )); then
        echo ""
    elif (( per >= 20 )); then
        echo ""
    elif (( per <= 20 )); then
        echo ""
    fi
}

function set_vol() {
    $(pamixer --set-volume $(printf "%.0f\n" "$1"))
}

if [ "$1" = "percent" ]; then
    percent
elif [ "$1" = "icon" ]; then
    icon
elif [ "$1" = "class" ]; then
    class
elif [ "$1" = "set_vol" ]; then
    set_vol "$2"
else
    echo "unknown option"
fi

