#!/bin/sh

bat=$(cat /sys/class/power_supply/BAT0/capacity)

function percent() {
    echo $bat
}

function icon() {
    if (( bat < 20 ));then
        echo ""
    elif (( bat < 40 ));then
        echo ""
    elif (( bat < 60 ));then
        echo ""
    elif (( bat < 80 ));then
        echo ""
    else
        echo ""
    fi
}

case "$1" in
    "percent") percent;;
    "icon") icon;;
    *) echo "Unknown command";;
esac

