#!/bin/bash

CACHE_DIR="$HOME/.cache/eww/"

if [ -f "$CACHE_DIR/dashboard.lock" ]; then
	rm "$CACHE_DIR/dashboard.lock"
	eww -c "$HOME/.config/eww/fool_moon/dashboard" close darken clock power media
	eww -c "$HOME/.config/eww/fool_moon/meters" close meters
	eww -c "$HOME/.config/eww/fool_moon/bar" open bar
	for i in $(bspc query -N -n .window.hidden -d);do
		bspc node $i -g hidden=off
	done
	pkill glava
else
	touch "$CACHE_DIR/dashboard.lock"
	eww -c "$HOME/.config/eww/fool_moon/dashboard" open-many darken clock power media 
	eww -c "$HOME/.config/eww/fool_moon/meters" open meters
	eww -c "$HOME/.config/eww/fool_moon/bar" close bar
	for i in $(bspc query -N -n .window -d);do
		bspc node $i -g hidden=on
	done
	glava 1> /dev/null &
fi

