#!/bin/sh

CACHE_DIR="$HOME/.cache/eww"
animate=$HOME/.config/eww/fool_moon/common/scripts/animations.bash

function toggle_state() {
	cat "$CACHE_DIR/toggle.state"
}

function follow() {

	$animate run -i "rot" -s 45 -e "ease_out_expo" -r

	if ! [ -f "$CACHE_DIR/rot.value" ];then
		mkdir -p "$CACHE_DIR"
		touch "$CACHE_DIR/rot.value"
	fi

	tail -F "$CACHE_DIR/rot.value" 2> /dev/null
}

function toggle() {
	if [ $(toggle_state) = "on" ];then
		echo "off" > "$CACHE_DIR/toggle.state"
		$animate run -i "rot" -s 45 -e "ease_out_expo" -r> "$CACHE_DIR/rot.value"
	else
		echo "on" > "$CACHE_DIR/toggle.state"
		$animate run -i "rot" -s 45 -e "ease_out_expo" > "$CACHE_DIR/rot.value"
	fi
}


case "$1" in
	"toggle") toggle;;
	"follow") follow;;
	*) echo "unknown command";;
esac

