#! /bin/sh

# wm parenting issue fix, see: https://www.reddit.com/r/bspwm/comments/267srd/comment/chotpgf/?utm_source=share&utm_medium=web2x&context=3
wmname LG3D
bash ~/.config/bspwm/launch.sh &

. "${HOME}/.cache/wal/colors.sh"

# Set the border colors.
bspc config normal_border_color "$color1"
bspc config active_border_color "$color2"
bspc config focused_border_color "$color15"

bspc monitor -d 一 二 三 四 五

bspc config border_width        1 
bspc config window_gap          10
bspc config top_padding		52

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true	

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
