#!/bin/bash

CACHE_DIR="$HOME/.cache/eww"
animate="$HOME/.config/eww/fool_moon/common/scripts/animations"
delta=2

function percent () {
    echo $(pamixer --get-volume) 
}

function icon() {
    local per=$(percent)
    local muted=$(pamixer --get-mute)

    if [ "$muted" = "true" ]; then
        echo "" 
    elif (( per >= 60 )); then
        echo "" 
    elif (( per >= 20 )); then
        echo "" 
    elif (( per <= 20 )); then
        echo "" 
    fi
}

function set_vol() {
    if [ -f "$CACHE_DIR/vol.value" ] && ! $animate is_locked "vol";then
        local val=$(printf "%.0f\n" "$1")
        pamixer --set-volume $val
        echo $val > "$CACHE_DIR/vol.value"
    fi
}

function toggle_mute() {
    pamixer --toggle-mute
}

function follow() {
    local scalar=$(percent)
    $animate run -i "vol" -s $scalar -e "ease_out_expo"

    if ! [ -f "$CACHE_DIR/vol.value" ];then
        mkdir -p "$CACHE_DIR"
        touch "$CACHE_DIR/vol.value"
    fi

    echo $(percent) > "$CACHE_DIR/vol.value"

    tail -F "$CACHE_DIR/vol.value" 2> /dev/null
}

function change() {
    [ "$1" = "up" ] && pamixer --increase $delta || pamixer --decrease $delta

    if [ -f "$CACHE_DIR/vol.value" ] && ! $animate is_locked "vol";then
        echo $(percent) > "$CACHE_DIR/vol.value"
	fi
}


case "$1" in
    "percent") percent;;
    "icon") icon;;
    "set") set_vol "$2";;
    "follow") follow "$2";;
    "change") change "$2";;
    "toggle-mute") toggle_mute;;
    *) echo "Unknown command";;
esac
