#!/bin/sh

CACHE_DIR="$HOME/.cache/eww"
animate="$HOME/.config/eww/common/scripts/animations.bash"
delta=5

function percent() {
    echo $(brightnessctl -m | cut -d "," -f 4 | sed 's/%//')
}

function change() {
    [ "$1" = "up" ] && brightnessctl set "+$delta%" 1> /dev/null || brightnessctl set "$delta%-" 1> /dev/null
    if [ -f "$CACHE_DIR/bright.value" ] && ! $animate is_locked "bright";then
        echo $(percent) > "$CACHE_DIR/bright.value"
    fi
}

function set_value() { 
    if [ -f "$CACHE_DIR/bright.value" ] && ! $animate is_locked "bright";then
        brightnessctl set "$1%" > /dev/null
        echo $(percent) > "$CACHE_DIR/bright.value"
    fi
}

function follow() {
    local scalar=$(percent)
    $animate run -i "bright" -s $scalar -e "ease_out_expo"

    if ! [ -f "$CACHE_DIR/bright.value" ];then
        mkdir -p "$CACHE_DIR"
        touch "$CACHE_DIR/bright.value"
    fi

    echo $(percent) > "$CACHE_DIR/bright.value"

    tail -F "$CACHE_DIR/bright.value" 2> /dev/null
}


case "$1" in
    "percent") percent;;
    "change") change "$2";;
    "set") set_value "$2";;
    "follow") follow;;
    *) echo "Unknown command";;
esac

