#!/bin/bash

CACHE_DIR="$HOME/.cache/eww"
JSON_DIR="$CACHE_DIR/sys.json"

function toggle_wifi() {
	local state=$(jq -r '.wifi_class' "$JSON_DIR")
	if [ "$state" = "wifi-on" ];then
		jq -c '.wifi_class = "wifi-off"' "$JSON_DIR" | sponge "$JSON_DIR"
		nmcli radio wifi off
	else
		jq -c '.wifi_class = "wifi-on"' "$JSON_DIR" | sponge "$JSON_DIR"
		nmcli radio wifi on 
	fi
}

function toggle_air() {
	local state=$(jq -r '.air_class' "$JSON_DIR")
	if [ "$state" = "air-on" ];then
		jq -c '.air_class = "air-off"' "$JSON_DIR" | sponge "$JSON_DIR"
		jq -c '.air_icon = ""' "$JSON_DIR" | sponge "$JSON_DIR"
		rfkill unblock wlan
		rfkill unblock bluetooth
	else
		jq -c '.air_class = "air-on"' "$JSON_DIR" | sponge "$JSON_DIR"
		jq -c '.air_icon = ""' "$JSON_DIR" | sponge "$JSON_DIR"
		rfkill block wlan
		rfkill block bluetooth
	fi
}

function toggle_dnd() {
	local state=$(jq -r '.dnd_class' "$JSON_DIR")
	if [ "$state" = "dnd-on" ];then
		jq -c '.dnd_class = "dnd-off"' "$JSON_DIR" | sponge "$JSON_DIR"
		jq -c '.dnd_icon = ""' "$JSON_DIR" | sponge "$JSON_DIR"
		dunstctl set-paused false
	else
		jq -c '.dnd_class = "dnd-on"' "$JSON_DIR" | sponge "$JSON_DIR"
		jq -c '.dnd_icon = ""' "$JSON_DIR" | sponge "$JSON_DIR"
		dunstctl set-paused true
	fi
}

function screenshot() {
	eww -c "$HOME/.config/eww/fool_moon/menu" close sys-menu
	flameshot gui
}

function toggle_night() {
	local state=$(jq -r '.night_class' "$JSON_DIR")
	if [ "$state" = "night-on" ];then
		jq -c '.night_class = "night-off"' "$JSON_DIR" | sponge "$JSON_DIR"
		jq -c '.night_icon = ""' "$JSON_DIR" | sponge "$JSON_DIR"
		redshift -x
	else
		jq -c '.night_class = "night-on"' "$JSON_DIR" | sponge "$JSON_DIR"
		jq -c '.night_icon = ""' "$JSON_DIR" | sponge "$JSON_DIR"
		redshift -P -O 5000
	fi
}

function follow() {
	tail -F "$JSON_DIR" 2> /dev/null
}

if ! [ -f "$JSON_DIR" ];then
	mkdir -p "$CACHE_DIR"
	touch "$JSON_DIR"
	echo '{"wifi_class":"wifi-on","air_icon":"","air_class":"air-off","dnd_icon":"","dnd_class":"dnd-off","night_icon":"","night_class":"night-off"}' > "$JSON_DIR"
fi

case "$1" in
	"toggle-wifi") toggle_wifi;;
	"toggle-blue") toggle_blue;;
	"toggle-air") toggle_air;;
	"toggle-dnd") toggle_dnd;;
	"toggle-night") toggle_night;;
	"screenshot") screenshot;;
	"follow") follow;;
	*) echo "unknown command";;
esac

