#!/bin/bash

animate="$HOME/.config/eww/fool_moon/scripts/animations"

function percent () {
	pamixer --default-source --get-volume
}

function icon() {
	local muted
	muted=$(pamixer --default-source --get-mute)
	if [ "$muted" = "true" ]; then
		echo "" 
	else
		echo "" 
	fi
}

function json() {
	echo "{\"percent\":$(percent),\"icon\":\"$(icon)\"}"
}

function set_val() {
	local val
	val=$(printf "%.0f\n" "$1")
	pamixer --default-source --set-volume "$val" 
}

function toggle_mute() {
	pamixer --default-source --toggle-mute
}

function follow() {
	local v
	v=$(json)
	echo "$v"
	while sleep 0.1; do
		local nv
		nv=$(json)
		[[ $v != "$nv" ]] && v=$nv && echo "$nv"
	done
}


function follow_animated() {
	local scalar
	scalar=$(percent)
    while read -r line; do
		echo "{\"percent\":$line,\"icon\":\"$(icon)\"}"
	done < <($animate run -i "mic" -s "$scalar" -e "ease_out_expo")
	follow
}

function change() {
	if [ "$1" = "up" ];then 
		pamixer --default-source --increase 1
	else 
		pamixer --default-source --decrease 1 
	fi
}

case "$1" in
	"set") set_val "$2";;
	"follow") follow "$2";;
	"follow-animated") follow_animated ;;
	"change") change "$2";;
	"toggle-mute") toggle_mute;;
	*) echo "Unknown command";;
esac
