#! /bin/sh

# wm parenting issue fix, see: https://www.reddit.com/r/bspwm/comments/267srd/comment/chotpgf/?utm_source=share&utm_medium=web2x&context=3
# wmname LG3D

EWW_DIR=$HOME/.config/eww/fool_moon

killall picom
killall dunst
killall eww

sxhkd &
dunst &
picom --config $HOME/.config/picom/picom.ini --experimental-backends &
feh --bg-fill ~/.config/wallpapers/fool_moon.jpg
eww -c $EWW_DIR/bar open bar
eww -c $EWW_DIR/menu daemon

bspc config normal_border_color "#1a1b26"
bspc config active_border_color "#364A73"
bspc config focused_border_color "#3c3c47"

bspc monitor -d 1 2 3 4 5 6 

bspc config border_width        1 
bspc config window_gap          10

bspc config pointer_modifier mod1
bspc config pointer_action1 resize_side
bspc config pointer_action1 resize_corner
bspc config pointer_action3 move

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true	

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc subscribe node_state | while read -r _ _ _ _ state flag; do
if [ "$state" != "fullscreen" ]; then
	continue
fi
if [ "$flag" == on ]; then
	eww -c $EWW_DIR/bar close bar 
else
	eww -c $EWW_DIR/bar open bar
fi
done &
