#!/bin/sh

EWW_DIR=$HOME/.config/eww/fool_moon/windows

killall compfy
killall dunst
killall eww

sxhkd &
dunst &
xsetroot -cursor_name left_ptr &
compfy --config "$HOME"/.config/picom/picom.ini &
feh --bg-fill "$HOME"/.config/wallpapers/fool_moon.jpg

eww -c "$EWW_DIR"/bar open bar
eww -c "$EWW_DIR"/start-menu daemon
eww -c "$EWW_DIR"/side-menu daemon
# eww -c "$EWW_DIR"/meters daemon

"$HOME"/.config/eww/fool_moon/scripts/system-toggles restore

