#!/bin/sh

EWW_DIR=$HOME/.config/eww/fool_moon

killall picom
killall dunst
killall eww

sxhkd &
dunst &
xsetroot -cursor_name left_ptr &
picom --config $HOME/.config/picom/picom.ini --experimental-backends &
feh --bg-fill ~/.config/wallpapers/fool_moon.jpg

eww -c $EWW_DIR/bar open bar
eww -c $EWW_DIR/menu daemon
eww -c $EWW_DIR/dashboard daemon
eww -c $EWW_DIR/meters daemon

$HOME/.config/eww/fool_moon/menu/scripts/sys restore

