#!/bin/sh

eww_menu="eww -c $HOME/.config/eww/fool_moon/menu"
CACHE_DIR="$HOME/.cache/eww"

function toggle_notifs() {
	# $eww_menu close sys-menu time-menu
	if [ -f "$CACHE_DIR/notif-menu.lock" ];then
		rm "$CACHE_DIR/notif-menu.lock"
		$eww_menu close unfocus
		$eww_menu close notif-menu
	else
		touch "$CACHE_DIR/notif-menu.lock"
		$eww_menu open notif-menu
	fi
}

function toggle_sys() {
	# $eww_menu close time-menu notif-menu
	if [ -f "$CACHE_DIR/sys-menu.lock" ];then
		rm "$CACHE_DIR/sys-menu.lock"
		$eww_menu close unfocus
		$eww_menu close sys-menu
	else
		touch "$CACHE_DIR/sys-menu.lock"
		$eww_menu open sys-menu
	fi
}

function toggle_time() {
	# $eww_menu close sys-menu notif-menu
	if [ -f "$CACHE_DIR/time-menu.lock" ];then
		rm "$CACHE_DIR/time-menu.lock"
		$eww_menu close unfocus
		$eww_menu close time-menu notif-menu
	else
		touch "$CACHE_DIR/time-menu.lock"
		$eww_menu open-many time-menu notif-menu
	fi
}

if ! [ -d "$CACHE_DIR" ];then
	mkdir -p "$CACHE_DIR"
fi

case "$1" in
	"toggle-notifs") toggle_notifs;;
	"toggle-sys") toggle_sys;;
	"toggle-time") toggle_time;;
	*) echo "Unknown command";;
esac

