#!/bin/sh

eww_menu="eww -c $HOME/.config/eww/fool_moon/menu"
CACHE_DIR="$HOME/.cache/eww"

function toggle_sys() {
	if [ -f "$CACHE_DIR/sys-menu.lock" ];then
		rm "$CACHE_DIR/sys-menu.lock"
		$eww_menu close unfocus
		$eww_menu close sys-menu
	else
		touch "$CACHE_DIR/sys-menu.lock"
		$eww_menu open sys-menu
	fi
}

function toggle_time() {
	if [ -f "$CACHE_DIR/time-menu.lock" ];then
		rm "$CACHE_DIR/time-menu.lock"
		$eww_menu close unfocus
		$eww_menu close time-menu 
		$eww_menu update time-vis=false
	else
		touch "$CACHE_DIR/time-menu.lock"
		$eww_menu open time-menu 
		$eww_menu update time-vis=true
	fi
}

if ! [ -d "$CACHE_DIR" ];then
	mkdir -p "$CACHE_DIR"
fi

case "$1" in
	"toggle-sys") toggle_sys;;
	"toggle-time") toggle_time;;
	*) echo "Unknown command";;
esac

